python3 /home/ubuntu/Desktop/titre/logi3_direct/A.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AACG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AACI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AACIU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AACIW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AADI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAIC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAMC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAME.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAOI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAON.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAPL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAQC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AATC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AAWW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABBV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABCB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABCL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABCM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABEO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABEV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABGI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABIO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABMD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABNB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABOS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABSI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABST.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABTX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABUS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ABVC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACAB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACABU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACAD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACAH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACAHU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACAHW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACAQ.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACAXR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACAXU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACAXW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACEL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACER.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACET.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACEV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACEVU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACGL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACGLN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACGLO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACHC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACHL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACHR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACHV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACII.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACIU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACIW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACMR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACNB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACON.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACONW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACOR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACQR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACQRU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACRO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACRS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACRX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACST.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACTD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACVA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ACXP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADAG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADAL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADAP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADBE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADCT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADER.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADERW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADES.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADEX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADGI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADIL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADMA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADMP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADNT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADOC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADOCR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADOCW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADPT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADRA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADRT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADSE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADSEW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADSK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADTH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADTHW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADTN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADTX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADUS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADVM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ADXN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEAC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEF.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEFC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEIS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEMD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AENZ.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEPPZ.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AER.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AERC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AERI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AES.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AESC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AESC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEVA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AESE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEYE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AEZS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFAC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFACW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFAQ.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFAQU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFAQW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFBI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFCG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFGB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFGC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFGD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFGE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFIB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFMD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFRM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFTR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AFYA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGAC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGBA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGBAR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGBAW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGCB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGCO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGEN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGFS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGFY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGGR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGGRU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGIL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGILW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGIO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGLE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGMH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGNC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGNCM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGNCN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGNCO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGNCP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGRI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGRIW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGRO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGRX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGTC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGTI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AGYS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AHCO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AHG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AHH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AHI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AHPA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AHPAU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AHPAW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AHPI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AHRN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AHRNU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AHT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIF.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIHS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIKI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIMAU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIMC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AINC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AINV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIRC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIRG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIRI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIRS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIRT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIRTP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIZ.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AIZN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AJG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AJRD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AJX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AJXA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKAM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKAN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKBA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKIC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKRO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKTS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKTX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKUS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AKYA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALBO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALCC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALCO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALDX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALEC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALEX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALF.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALFIW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALGM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALGN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALGS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALGT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALHC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALIT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALJJ.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALKS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALLE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALLG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALLK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALLO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALLR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALLT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALLY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALNA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALNY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALOR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALORU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALORW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALOT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALPA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALPAW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALPN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALPP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALRM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALRN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALRS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALSA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALSAR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALSAW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALSN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALTG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALTO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALTR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALTU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALTUU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALTUW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALVR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALXO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALYA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ALZN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMAL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMAM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMAO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMAOW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMAT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMBA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMBC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMBO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMBP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMCI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMCIW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMCR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMCX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AME.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMED.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMEH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMGN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMKR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMLX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMNB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMOT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMOV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMPE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMPG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMPGW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMPH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMPI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMPL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMPS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMPY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMRC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMRK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMRN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMRS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMRX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMSC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMSF.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMST.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMSWA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMTB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMTD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMTI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMTX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMWD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMWL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMYT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AMZN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANAB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANAC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANAT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANDE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANEB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANET.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANF.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANGH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANDE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANEB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANET.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANF.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANGH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANGHW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANGI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANGN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANGO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANIK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANIP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANIX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANPC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANSS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANTE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANTM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANTX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANVS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANZU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANZUU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ANZUW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AOD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AOGO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AOGOW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AOMR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AON.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AORT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AOS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AOSL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AOUT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APAC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APACW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APAM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APCA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APCX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APCXW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APDN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APEI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APEN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APGB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/API.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APLD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APLE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APLS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APLT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APMI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APMIU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APMIW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APOG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APPF.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APPH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APPHW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APPN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APPS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APRE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APRN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APSG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APTMU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APTMW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APTO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APTS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APTV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APTX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APVO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APWC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APXI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APXIU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APXIW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/APYX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AQB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AQMS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AQN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AQNA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AQNB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AQNU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AQST.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AQUA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARAV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARAY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARBE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARBEW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARBG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARBGU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARBGW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARBK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARCB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARCC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARCE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARCH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARCK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARCKU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARCKW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARCO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARCT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARDC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARDS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARDX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AREB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AREBW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AREC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AREN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARES.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARGD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARGO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARGU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARGUU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARGUW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARGX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARHS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARIS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARIZ.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARIZR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARIZU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARIZW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARKO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARKOW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARKR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARLO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARLP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARMK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARMP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARNC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AROC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AROW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARQQ.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARQQW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARQT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARRW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARRWU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARRWW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARRY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARTE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARTEW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARTL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARTLW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARTNA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARTW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARVL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARVN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARWR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARYD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ARYE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASAI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASAN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASAQ.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASAX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASCA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASCAR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASCBU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASGI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASGN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASIX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASLE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASLN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASMB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASML.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASND.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASNS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASPA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASPAU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASPAW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASPC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASPCU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASPCW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASPN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASPS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASPU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASRT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASRV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASTC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASTE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASTL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASTLW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASTR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASTS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASTSW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASUR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASXC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASYS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ASZ.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATAI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATAK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATAKR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATAKU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATAKW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATAQ.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATAX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATCO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATCOL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATCX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATEC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATEK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATEN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATER.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATEX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATGE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATHE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATHM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATHX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATIF.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATIP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATKR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATLC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATLCL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATLCP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATLO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATNF.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATNFW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATNI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATNM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATNX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATOM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATOS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATRA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATRC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATRI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATNFW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATNI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATNM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATNX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATOM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATOS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATRA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATRC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATRI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATRO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATRS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATSG.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATTO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATUS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATVC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATVCW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATVI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATXI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATXS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/ATY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUBAP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUBN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUBN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUBAP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUDC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUGX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUID.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUMN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUPH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AURA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AURC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AURCU.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AURCW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUROW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUST.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUTL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUTO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUUD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUUDW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUVI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUVIP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUVIP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AUY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVAC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVACW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVAH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVAL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVAN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVAV.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVB.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVCO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVCT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVCTW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVD.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVDL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVDX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVEO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVGO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVGOP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVGR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVHI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVHIW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVID.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVIR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVLR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVNS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVNT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVNW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVPT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVPTW.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVRO.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVT.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVTE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVTR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVTX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVXL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVY.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AVYA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AWF.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AWH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AWI.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AWK.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AWP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AWR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AWRE.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AWX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXAC.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXDX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXGN.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXH.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXL.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXLA.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXNX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXNX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXNX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXNX.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXON.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXP.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXR.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXS.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/AXSM.py &
python3 /home/ubuntu/Desktop/titre/logi3_direct/%launcher%
